name: CI - .NET Test (Triggered by Push and PR)

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # .NETのバージョン指定

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Run tests
      run: dotnet test --no-build -c Release